apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-and-build-reproducer-plr-
spec:
  pipelineRef:
    name: test-and-build-reproducer
  serviceAccountName: case03752258-pipeline-sa
  params:
    - name: image-tag
      value: 50c30e44716abd0588d6a87687a43a2e67311a67
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: maven-settings
      configMap:
        name: maven-settings